version: '3.9'
services:
  marco_customer_postgres:
    container_name: marco_customer_db
    image: postgres:15.1-alpine
    volumes:
      - marco_customer_pg_data:/data/postgres
    environment:
      POSTGRES_USER: alaa
      POSTGRES_PASSWORD: alaa1234
      POSTGRES_DB: marco_customers
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - marco_customer_network
    restart: unless-stopped

  marco_fraud_postgres:
    container_name: marco_fraud_db
    image: postgres:15.1-alpine
    volumes:
      - marco_fraud_pg_data:/data/postgres
    environment:
      POSTGRES_USER: alaa
      POSTGRES_PASSWORD: alaa1234
      POSTGRES_DB: marco_frauds
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    networks:
      - marco_fraud_network
    restart: unless-stopped

networks:
  marco_customer_network:
    driver: bridge
  marco_fraud_network:
    driver: bridge


volumes:
  marco_customer_pg_data:
  marco_fraud_pg_data: